import type { ShelfBook } from "./shelf";
import { daysFromToday } from "./dates";

export const EXAMPLE_SHELF = (): ShelfBook[] => [
  {
    id: "ex-1",
    title: "Case Closed Vol. 3",
    author: "Gosho Aoyama",
    coverUrl: "https://covers.openlibrary.org/b/id/863436-M.jpg",
    pageCount: 184,
    status: "reading",
    pagesRead: 133,
    startedAt: daysFromToday(-3),
  },
  {
    id: "ex-2",
    title: "Omniscient Reader's Viewpoint Vol. 1",
    author: "sing N song",
    coverUrl: "https://covers.openlibrary.org/b/id/14321241-M.jpg",
    pageCount: 260,
    status: "want",
    pagesRead: 0,
  },
  {
    id: "ex-3",
    title: "Violet Evergarden, Side Story, KA Esuma Bunko",
    coverUrl: "https://covers.openlibrary.org/b/id/9380113-M.jpg",
    author: "Kana Akatsuki",
    pageCount: 374,
    status: "scheduled",
    pagesRead: 0,
    startDate: daysFromToday(7),
  },
  {
    id: "ex-4",
    title: "Harry Potter and the Goblet of Fire",
    author: "J.K. Rowling",
    coverUrl: "https://covers.openlibrary.org/b/id/12059372-M.jpg",
    pageCount: 636,
    status: "scheduled",
    pagesRead: 0,
    startDate: daysFromToday(-2),
  },
  {
    id: "ex-5",
    title: "Frieren: Beyond Journey's End, Vol. 1",
    author: "Kanehito Yamada & Tsukasa Abe",
    coverUrl: "https://covers.openlibrary.org/b/id/11075074-M.jpg",
    pageCount: 192,
    status: "finished",
    pagesRead: 192,
    startedAt: daysFromToday(-40),
    finishedAt: daysFromToday(-28),
  },
];
